### ISSUE TITLE
Greek Zodiacs

### ISSUE THREAD

**Issue by hargikas** [crusat/python-zodiac-sign#3]
You can add this in order to support Zodiacs in Greek:

    el_dict = (
        (0, "Κριός"),
        (1, "Ταύρος"),
        (2, "Δίδυμοι"),
        (3, "Καρκίνος"),
        (4, "Λέων"),
        (5, "Παρθένος"),
        (6, "Ζυγός"),
        (7, "Σκορπιός"),
        (8, "Τοξότης"),
        (9, "Αιγόκερως"),
        (10, "Υδροχόος"),
        (11, "Ιχθείς"),
    )
    
    language_dict = {
        'en_US': en_dict,
        'ru_RU': ru_dict,
        'pt_BR': pt_dict,
        'pt_PT': pt_dict,
    	'el': el_dict,
    	'el_CY': el_dict,
    	'el_GR': el_dict,
        None: en_dict
    }

**Comment by crusat** [comment]
Thank you! Updated!
