### ISSUE TITLE
Locale issue.

### ISSUE THREAD

**Issue by mrweisu** [crusat/python-zodiac-sign#4]
The code needs to be changed like this:

def _(word_index):
    language = locale.getlocale()
    return language_dict.get(language[0], language_dict.get('en_US'))[word_index][1]

As of now the code is
def _(word_index):
    language = locale.getlocale()
    return language_dict.get(language[0], 'en_US')[word_index][1]

For me, 
language = locale.getlocale()
language[0]
>>>'English_United States'

For the code as of now, 'English_United States' is not included in the language_dict dictionary. So a string 'en_US' is returned. And you can see there will be errors later.

**Comment by crusat** [comment]
Thanks! Fixed and updated! :)
